import { useEffect, useState } from "react";
import { api } from "../api/api";
import Layout from "../components/Layout";
import {
  Users,
  BookOpen,
  IndianRupee,
  AlertCircle,
  Activity,
} from "lucide-react";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

function calculatePendingDues(students = [], batches = [], fees = []) {
  const allDues = [];
  const now = new Date();
  const currentMonthIdx = now.getMonth();
  const currentYear = now.getFullYear();

  students.forEach((student) => {
    const sBatches =
      student.studentBatches && student.studentBatches.length > 0
        ? student.studentBatches
        : student.batchId
        ? [{ batchId: student.batchId, finalFee: student.finalFee }]
        : [];

    sBatches.forEach((sb) => {
      const batch = batches.find((b) => b.id === sb.batchId);
      if (!batch) return;

      const targetAmount =
        sb.finalFee !== undefined && sb.finalFee !== null
          ? sb.finalFee
          : batch.monthlyFee;

      let iterMonth = MONTHS.indexOf(batch.startMonth);
      let iterYear = Number(batch.startYear);

      if (iterMonth < 0 || !iterYear) {
        const joinDate = new Date(student.joinDate);
        if (!isNaN(joinDate.getTime())) {
          iterMonth = joinDate.getMonth();
          iterYear = joinDate.getFullYear();
        } else {
          iterMonth = 0;
          iterYear = currentYear;
        }
      }

      while (
        iterYear < currentYear ||
        (iterYear === currentYear && iterMonth <= currentMonthIdx)
      ) {
        const monthName = MONTHS[iterMonth];

        const records = fees.filter(
          (f) =>
            f.studentId === student.id &&
            (f.batchId === batch.id || (!f.batchId && sBatches.length === 1)) &&
            f.month === monthName &&
            Number(f.year) === iterYear
        );

        const paidSum = records
          .filter((f) => f.status === "paid")
          .reduce((sum, f) => sum + Number(f.amount), 0);

        const pendingBalance = targetAmount - paidSum;

        if (pendingBalance > 0) {
          allDues.push({
            id: `due-${student.id}-${batch.id}-${monthName}-${iterYear}`,
            studentId: student.id,
            batchId: batch.id,
            month: monthName,
            year: iterYear,
            amount: pendingBalance,
            status: "pending",
            isPartial: paidSum > 0,
            isAutoGenerated: true,
          });
        }

        iterMonth++;
        if (iterMonth > 11) {
          iterMonth = 0;
          iterYear++;
        }
      }
    });
  });

  return allDues;
}

export default function Dashboard() {
  const [data, setData] = useState({
    students: [],
    batches: [],
    fees: [],
  });

  const load = async () => {
    const students = await api.getStudents();
    const batches = await api.getBatches();
    const fees = await api.getFees();
    setData({ students, batches, fees });
  };

  useEffect(() => {
    load();
  }, []);

  const collected = data.fees
    .filter((f) => f.status === "paid")
    .reduce((a, b) => a + b.amount, 0);

  const pendingDues = calculatePendingDues(data.students, data.batches, data.fees);
  const pending = pendingDues.reduce((a, b) => a + b.amount, 0);

  const cards = [
    {
      label: "Students",
      value: data.students.length,
      icon: Users,
      color: "text-indigo-500",
    },
    {
      label: "Batches",
      value: data.batches.length,
      icon: BookOpen,
      color: "text-blue-500",
    },
    {
      label: "Collected",
      value: `₹${collected}`,
      icon: IndianRupee,
      color: "text-green-500",
    },
    {
      label: "Pending",
      value: `₹${pending}`,
      icon: AlertCircle,
      color: "text-amber-500",
    },
  ];

  return (
    <Layout
      title="Dashboard"
      subtitle="Overview of your institute performance"
    >

      {/* KPI CARDS */}
      <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-5 mb-6 sm:mb-8">

        {cards.map((c, i) => {
          const Icon = c.icon;

          return (
            <div
              key={i}
              className="bg-white border rounded-2xl p-4 sm:p-5 shadow-sm hover:shadow-md transition"
            >

              <Icon className={`${c.color} h-5 w-5`} />

              <p className="text-lg sm:text-2xl font-black mt-2 sm:mt-3 text-slate-900">
                {c.value}
              </p>

              <p className="text-xs sm:text-sm text-slate-500">
                {c.label}
              </p>

            </div>
          );
        })}

      </div>

      {/* RECENT ACTIVITY */}
      <div className="bg-white border rounded-2xl p-4 sm:p-6">

        <div className="flex items-center gap-2 mb-4">
          <Activity className="h-5 w-5 text-slate-600" />
          <h3 className="font-bold text-slate-900">Recent Activity</h3>
        </div>

        {data.students.length === 0 ? (
          <p className="text-slate-400 text-sm">
            No recent activity
          </p>
        ) : (
          <div className="space-y-1">

            {data.students.slice(0, 6).map((s) => (
              <div
                key={s.id}
                className="flex items-center gap-3 py-3 border-b last:border-0"
              >

                <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-full bg-indigo-500 text-white flex items-center justify-center font-bold text-sm sm:text-base">
                  {s.name?.charAt(0)}
                </div>

                <div className="min-w-0">
                  <p className="font-medium text-slate-900 truncate">
                    {s.name}
                  </p>
                  <p className="text-xs text-slate-500 truncate">
                    {s.mobile}
                  </p>
                </div>

              </div>
            ))}

          </div>
        )}

      </div>

    </Layout>
  );
}