import { useEffect, useState } from "react";
import { api } from "../api/api";
import Layout from "../components/Layout";
import {
  Download,
  Users,
  BookOpen,
  IndianRupee,
  AlertCircle,
  Calendar,
} from "lucide-react";

const MONTHS = [
  "All Months",
  "January","February","March","April","May","June",
  "July","August","September","October","November","December"
];

export default function Reports() {
  const [data, setData] = useState({
    students: [],
    batches: [],
    fees: [],
  });

  const [filter, setFilter] = useState({
    month: "All Months",
    year: "All Years",
  });

  const load = async () => {
    const students = await api.getStudents();
    const batches = await api.getBatches();
    const fees = await api.getFees();
    setData({ students, batches, fees });
  };

  useEffect(() => {
    load();
  }, []);

  const filterFeeRecords = (feesList) => {
    return feesList.filter(f => {
      const monthMatch = filter.month === "All Months" || f.month === filter.month;
      const yearMatch = filter.year === "All Years" || f.year.toString() === filter.year;
      return monthMatch && yearMatch;
    });
  };

  // ── DUES CALCULATION LOGIC ──────────────────────────────────────────────────
  
  const getAllPendingDues = () => {
    const allDues = [];
    const now = new Date();
    const currentMonthIdx = now.getMonth();
    const currentYear = now.getFullYear();

    data.students.forEach(student => {
      const batch = data.batches.find(b => b.id === student.batchId);
      if (!batch) return;

      const targetAmount = student.finalFee || batch.monthlyFee;

      // Start from Batch start month/year
      let iterMonth = MONTHS.indexOf(batch.startMonth) - 1; 
      let iterYear = batch.startYear;

      if (iterMonth < 0 || !iterYear) {
        const joinDate = new Date(student.joinDate);
        iterMonth = joinDate.getMonth();
        iterYear = joinDate.getFullYear();
      }

      while (iterYear < currentYear || (iterYear === currentYear && iterMonth <= currentMonthIdx)) {
        const monthName = MONTHS[iterMonth + 1];
        
        // Find ALL records for this student/month/year
        const records = data.fees.filter(f => 
          f.studentId === student.id && 
          f.month === monthName && 
          f.year === iterYear
        );

        const paidSum = records
          .filter(f => f.status === "paid")
          .reduce((sum, f) => sum + f.amount, 0);

        const pendingBalance = targetAmount - paidSum;

        if (pendingBalance > 0) {
          allDues.push({
            id: `due-${student.id}-${monthName}-${iterYear}`,
            studentId: student.id,
            batchId: student.batchId,
            month: monthName,
            year: iterYear,
            amount: pendingBalance,
            status: "pending",
            isPartial: paidSum > 0,
            isAutoGenerated: true
          });
        }

        iterMonth++;
        if (iterMonth > 11) {
          iterMonth = 0;
          iterYear++;
        }
      }
    });

    return allDues;
  };

  const allPendingDues = getAllPendingDues();
  const filteredPendingDues = filterFeeRecords(allPendingDues);
  const filteredPaidFees = filterFeeRecords(data.fees.filter(f => f.status === "paid"));

  const totalCollected = filteredPaidFees.reduce((a, b) => a + b.amount, 0);
  const totalPending = filteredPendingDues.reduce((a, b) => a + b.amount, 0);

  const exportCSV = () => {
    const headers = ["Student", "Batch", "Month", "Year", "Amount", "Status"];

    const rows = data.fees.map((f) => {
      const student = data.students.find((s) => s.id === f.studentId);
      const batch = data.batches.find((b) => b.id === f.batchId);

      return [
        student?.name || "",
        batch?.name || "",
        f.month,
        f.year,
        f.amount,
        f.status,
      ];
    });

    const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join(
      "\n"
    );

    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "edufees-report.csv";
    a.click();
  };

  const stats = [
    {
      label: "Students",
      value: data.students.length,
      icon: Users,
      color: "text-indigo-600",
    },
    {
      label: "Batches",
      value: data.batches.length,
      icon: BookOpen,
      color: "text-blue-600",
    },
    {
      label: "Collected",
      value: `₹${totalCollected}`,
      icon: IndianRupee,
      color: "text-green-600",
    },
    {
      label: "Pending",
      value: `₹${totalPending}`,
      icon: AlertCircle,
      color: "text-amber-600",
    },
  ];

  return (
    <Layout title="Reports" subtitle="Analytics & export data">

      {/* FILTERS */}
      <div className="bg-white border rounded-2xl p-4 mb-6 flex flex-col sm:flex-row items-center gap-4">
        <div className="flex items-center gap-2 text-slate-500 min-w-fit">
          <Calendar size={18} />
          <span className="text-sm font-medium">Filter by:</span>
        </div>

        <select
          value={filter.month}
          onChange={(e) => setFilter({ ...filter, month: e.target.value })}
          className="border rounded-xl p-2 w-full sm:w-40 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
        >
          {MONTHS.map(m => (
            <option key={m} value={m}>{m}</option>
          ))}
        </select>

        <select
          value={filter.year}
          onChange={(e) => setFilter({ ...filter, year: e.target.value })}
          className="border rounded-xl p-2 w-full sm:w-32 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
        >
          <option value="All Years">All Years</option>
          {[...new Array(5)].map((_, i) => {
            const y = (new Date().getFullYear() - i).toString();
            return <option key={y} value={y}>{y}</option>;
          })}
        </select>

        <div className="flex-1" />

        <button
          onClick={exportCSV}
          className="w-full sm:w-auto bg-slate-900 text-white px-4 py-2 rounded-xl flex items-center justify-center gap-2 hover:bg-slate-800 transition text-sm"
        >
          <Download size={16} /> Export CSV
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {stats.map((s, i) => {
          const Icon = s.icon;
          return (
            <div
              key={i}
              className="bg-white border rounded-2xl p-4 sm:p-5 shadow-sm"
            >
              <Icon className={`${s.color} mb-2`} />
              <p className="text-xl sm:text-2xl font-black text-slate-900">
                {s.value}
              </p>
              <p className="text-xs sm:text-sm text-slate-500">
                {s.label}
              </p>
            </div>
          );
        })}
      </div>

      {/* Main Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* Fee Overview */}
        <div className="bg-white border rounded-2xl p-5">
          <h2 className="font-bold mb-4 text-slate-900">Fee Overview</h2>

          <div className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span>Total Records</span>
              <span className="font-bold">{data.fees.length}</span>
            </div>

            <div className="flex justify-between">
              <span>Total Paid Records</span>
              <span className="font-bold">{filteredPaidFees.length}</span>
            </div>

            <div className="flex justify-between">
              <span>Total Pending Dues</span>
              <span className="text-amber-600 font-bold">
                {filteredPendingDues.length}
              </span>
            </div>
          </div>
        </div>

        {/* Clean Insights */}
        <div className="bg-gradient-to-br from-slate-900 to-slate-800 text-white rounded-2xl p-5 sm:p-6">
          <h2 className="font-bold mb-3">Insights</h2>

          <p className="text-sm text-slate-300 leading-relaxed">
            • Fee collection tracking is active <br />
            • Pending payments require follow-up <br />
            • Batch-wise reporting helps better management <br />
            • Use export for financial analysis
          </p>
        </div>

      </div>

      {/* Pending Students List */}
      <div className="mt-6">
        <div className="bg-white border rounded-2xl p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <AlertCircle className="text-amber-500" size={20} />
            <h2 className="font-bold text-slate-900">Pending Payments Details</h2>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b text-slate-500">
                  <th className="pb-3 font-medium">Student Name</th>
                  <th className="pb-3 font-medium">Batch</th>
                  <th className="pb-3 font-medium">Month/Year</th>
                  <th className="pb-3 font-medium text-right">Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {filteredPendingDues.length > 0 ? (
                  filteredPendingDues.map(f => {
                    const student = data.students.find(s => s.id === f.studentId);
                    const batch = data.batches.find(b => b.id === f.batchId);
                    return (
                      <tr key={f.id} className="text-slate-700 hover:bg-slate-50">
                        <td className="py-3">
                          <p className="font-medium">{student?.name || "Unknown"}</p>
                          {f.isPartial ? (
                            <span className="text-[10px] bg-amber-50 text-amber-500 px-1 rounded">PARTIAL</span>
                          ) : f.isAutoGenerated && (
                            <span className="text-[10px] bg-red-50 text-red-500 px-1 rounded">MISSING</span>
                          )}
                        </td>
                        <td className="py-3 text-slate-500">{batch?.name || "N/A"}</td>
                        <td className="py-3 text-slate-500">{f.month} {f.year}</td>
                        <td className="py-3 text-right font-bold text-slate-900">₹{f.amount}</td>
                      </tr>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan="4" className="py-10 text-center text-slate-400 italic">
                      All fees are up to date! No pending payments.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </Layout>
  );
}